/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ElTreeNode: typeof import('element-plus/es')['ElTreeNode']
}
